export const ADD_COMMENT = 'ADD_COMMENT';
export const MENUS_LOADING = 'MENUS_LOADING';
export const MENUS_FAILED = 'MENUS_FAILED';
export const ADD_MENUS = 'ADD_MENUS';
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';
export const PROMOS_LOADING = 'PROMOS_LOADING';
export const ADD_PROMOS = 'ADD_PROMOS';
export const PROMOS_FAILED = 'PROMOS_FAILED';

export const AUTHORS_LOADING = 'AUTHORS_LOADING';
export const ADD_AUTHORS = 'ADD_AUTHORS';
export const AUTHORS_FAILED = 'AUTHORS_FAILED';